"""empty message

Revision ID: 002d26991193
Revises: 4b83d3624490
Create Date: 2022-05-29 14:52:57.981411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002d26991193'
down_revision = '4b83d3624490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
