"""empty message

Revision ID: 2da3687c69ba
Revises: 35c0adaa1343
Create Date: 2022-05-29 23:16:44.452516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da3687c69ba'
down_revision = '35c0adaa1343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_facebook_link_key', 'Artist', type_='unique')
    op.drop_constraint('Artist_image_link_key', 'Artist', type_='unique')
    op.drop_constraint('Artist_website_link_key', 'Artist', type_='unique')
    op.drop_constraint('Venue_facebook_link_key', 'Venue', type_='unique')
    op.drop_constraint('Venue_image_link_key', 'Venue', type_='unique')
    op.drop_constraint('Venue_website_link_key', 'Venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Venue_website_link_key', 'Venue', ['website_link'])
    op.create_unique_constraint('Venue_image_link_key', 'Venue', ['image_link'])
    op.create_unique_constraint('Venue_facebook_link_key', 'Venue', ['facebook_link'])
    op.create_unique_constraint('Artist_website_link_key', 'Artist', ['website_link'])
    op.create_unique_constraint('Artist_image_link_key', 'Artist', ['image_link'])
    op.create_unique_constraint('Artist_facebook_link_key', 'Artist', ['facebook_link'])
    # ### end Alembic commands ###
