"""empty message

Revision ID: 846a0904bc44
Revises: ff99c8cd03e1
Create Date: 2022-05-26 20:09:08.524276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846a0904bc44'
down_revision = 'ff99c8cd03e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Venue', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created_date')
    op.drop_column('Artist', 'created_date')
    # ### end Alembic commands ###
